### ISSUE TITLE
Note excerpt source

### ISSUE THREAD

**Issue by natejacobson** [washingtonstateuniversity/WSUWP-spine-parent-theme#136]
I would be helpful to add a class on the article-summary wrapper denoting from whence the excerpt has been pulled in order to account for possible styling discrepancies within feeds with heterogenous excerpts.

  https://github.com/washingtonstateuniversity/WSUWP-spine-parent-theme/blob/master/articles/post.php#L22

This was specifically raised by @charlesjdillon who is wrangling excerpts generated from "read-more" breaks (which come wrapped in TinyMCE's auto generated  p tags) and custom crafted excerpts which arrive unadorned.

The classes might be something like `break-excerpt`, `concatenated-excerpt`, `custom-exert`, and `content-excerpt`.

**Comment by jeremyfelt** [comment]
Fixed in #166
