### ISSUE TITLE
Enlarge full screen toggle when in page builder

### ISSUE THREAD

**Issue by MichelleFelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#168]
Request to make full screen toggle larger or actually 'full screen' when used. Currently it is only 1/2" or so larger than the standard window.

![screen shot 2015-01-14 at 9 31 53 am](https://cloud.githubusercontent.com/assets/6111174/5748116/3cdfd49a-9bf2-11e4-8ec8-7723591ba422.png)

**Comment by jeremyfelt** [comment]
Good catch, this is fixed for the next release. :)
