### ISSUE TITLE
Update styles on Make Editor to match screen size

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#170]
We can do a little bit to make the style of the editor a bit better. Noting some stuff here to pick up on later.

* Remove max height from `ttmake-overlay-body`
* Use jQuery to resize the MCE editor once the overlay is show in the Builder's overlay.js with something along the lines of `jQuery(window).height() - 350` for a decent approximate height.
* Change default styles for the overlay wrapper to something along the lines of:

```
#ttfmake-tinymce-overlay .ttfmake-overlay-wrapper {
	width: auto !important;
	height: auto !important;
	top: 75px !important;
	left: 75px !important;
	right: 75px !important;
	bottom: 75px !important;
	margin-left: 0 !important;
	margin-top: 0 !important;
}
```

**Comment by natejacobson** [comment]
And <dl>, <dt>, <dd> support is right around the corner, right? :)

**Comment by jeremyfelt** [comment]
Not sure? I don't see it as an open issue in the repo. :wink:

**Comment by natejacobson** [comment]
Oh well, then. Shucks.

**Comment by jeremyfelt** [comment]
Impending doom awaits this issue in #171 and #173. We can address future style changes elsewhere.
