### ISSUE TITLE
Change Spine header link text for campus locations

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#201]
We allow campus locations to change the mark and the URL used in the Spine header. The text attached to this link stays at "Washington State University" on each.

Should this change to match the specific location?

Also worth considering is foundation.wsu.edu, which currently uses "The Campaign for Washington State University".

**Comment by natejacobson** [comment]
Yes. Makes sense to carry the solution all the way through.

**Comment by jeremyfelt** [comment]
We should also change the defaults for social icons to the various campus accounts if they haven't been manually altered.
