### ISSUE TITLE
Make use of background image and mobile background image in section settings

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#203]
We capture data for background image and mobile background image in section settings but then don't do anything with it. On wsu.edu, we have Javascript that processes this. Now that the solution is stable, we should make it happen for everybody.

If we don't do this soon enough, there's a chance that others will implement custom JS that makes use of this data. At that point, back-compat will be tougher.

**Comment by natejacobson** [comment]
I agree, @jeremyfelt. But I haven't landed on the right way to do this when it's done automatically. There's no, background-image: none !important, though one can force the result by setting the background-size to 0 0. In this case, though, you're referring to instances when a background image has been manually assigned to a section, right? In that case, yeah... we shouldn't require js for that.

**Comment by jeremyfelt** [comment]
Yes, when the section settings are used to apply the `data-background` attribute.

This is the JS used on wsu.edu, I think we should stick to something similarly (exactly?) simple. Other background related style attributes could be styled accordingly through custom CSS, all we need to worry about is the image.

```
process_section_backgrounds = function() {
	var $bg_sections = $('.section-wrapper-has-background');

	$bg_sections.each( function() {
		var background_image = $(this).data('background');
		$(this).css('background-image', 'url(' + background_image + ')' );
	});
};
```

**Comment by jeremyfelt** [comment]
And actually, this should also make use of the mobile version of the background instead if it exists and the screen width makes sense.

**Comment by natejacobson** [comment]
The html equivalent of that, yes. We should supply default settings for the other background attributes as well in the Spine parent theme style.css.

**Comment by jeremyfelt** [comment]
I'll actually push a bit for JS being the right answer here. :)

This is especially important for sites with large background images on sections as it allows all other page content/styles to load before going to download additional assets. Crucial parts are then delivered to the browser before everything else. If JS is disabled, the background images applied to sections should not be crucial to other content.

**Comment by jeremyfelt** [comment]
I'll get this in shortly using our current WSU Home, etc.. method.
