### ISSUE TITLE
Remove WSU Background from Bookmark theme by default

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#207]
* Not many people enjoy this currently. We've gotten quite a bit of feedback.
* It is pushing many people to skeletal, where a default style is not applied. Though bookmark isn't too styled out.
* If we do keep it, there should be an option to change the site wide background through a UI, with an option to choose none.

**Comment by natejacobson** [comment]
Sounds good.
