### ISSUE TITLE
Child pages not in the navigation should cause their parent page to be active in navigation

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#228]

**Comment by natejacobson** [comment]
This should also be combined with #85. The option in cases like this should be the ability to manually choose the preferred active link.

**Comment by jeremyfelt** [comment]
Agreed with combination with #85, as it's very similar. However, if a parent->child relationship is defined, wouldn't it make sense to highlight the parent automatically if the child did not exist?

**Comment by natejacobson** [comment]
Yes. Probably. I'm just wondering if there are times when you wouldn't want that behavior. Maybe if the metabox in #85 also enabled the ability to choose none, then you'd have the best of both world. By default, it highlighted the parent, but you could prevent it from doing so. The use case I'm trying to preserve may be vanishingly small, though. (Autocomplete keeps changing metabox to meatball. Now a meatball hoagie sounds good.)

**Comment by jeremyfelt** [comment]
Well, the shortcode UI is shortcake (https://wordpress.org/plugins/shortcode-ui/)... maybe we need a Meatball UI.

I think that makes sense. Sane auto-behavior with an override.

**Comment by jeremyfelt** [comment]
Noting that this came up in open labs today. It magically works in BU Navigation.
