### ISSUE TITLE
Audit and document the population of main header, HTML title, and page title

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#274]
We need to be able to properly describe the consequences of changing various settings in WordPress and in the Customizer that modify the display of the titles, sup/sub, etc...

Documentation should live on web.wsu.edu.

From this process, we can create additional issues in GitHub that we tackle individually.

**Comment by philcable** [comment]
Page up at https://web.wsu.edu/wordpress/themes/spine-elements/header/. Not yet added to site menu.

**Comment by philcable** [comment]
Added the page mentioned above to the site menu, only took two years and change :).
