### ISSUE TITLE
Restore menu item IDs

### ISSUE THREAD

**Issue by natejacobson** [washingtonstateuniversity/WSUWP-spine-parent-theme#32]
I'm very happy with our much reduced class assignments on menu items, but in anticipation of in-page navigation (and navigation that highlights with scrolling), we should restore the IDs we are stripping with the `spine-abridged_menu_classes` function.

    function spine_abbridged_menu_classes( $classes ) {
	if ( in_array( 'current-menu-item', $classes ) || in_array( 'current_page_parent', $classes ) ) {
		return array( 'current' );
	}

	return array();
     }

I did take a stab at this, but without success.

**Comment by jeremyfelt** [comment]
Should we still think of doing this? Similar to 9c4a40d0446, we can just append `current` instead of stripping everything else.

**Comment by philcable** [comment]
Closing per discussion with Jeremy.
