### ISSUE TITLE
Right Side Gutter overlaps Embed on Mobile

### ISSUE THREAD

**Issue by blairlierman** [washingtonstateuniversity/WSUWP-spine-parent-theme#346]
Can we reduce the right padding used for the right side gutter on mobile devices with small screen widths?

The right side gutter is overlapping the iDonate embed when viewed on phone screens with a width of less than 372 pixels, such as the Samsung Galaxy S5 and S6 and iPhone 5.

Example (using Chrome Dev Tools device emulation and the WSU Spine): 
![Example of Issue](http://content.screencast.com/users/WSU-Foundation/folders/Snagit/media/c3feb127-3df1-4bdc-b798-c1f9bfa6d40a/10.06.2016-11.08.png)

There appears to be extra padding that is overlapping the embed on the div with the class "column one". 
![Element and CSS example](http://content.screencast.com/users/WSU-Foundation/folders/Snagit/media/27487038-726d-4a61-81e7-91712b961031/10.06.2016-11.14.png)

If I adjust the padding-right to 1rem, the overlap goes away.

**Comment by charlesjdillon** [comment]
I am not exactly sure if your using WordPress to embed your iDonate. If you are, we have an option in customize to adjust the padding under Style Options. I believe it adds the class spacing-tight to the #jacket.
![screen shot 2016-10-06 at 11 36 14 am](https://cloud.githubusercontent.com/assets/4007184/19165648/74606958-8bb9-11e6-8ad9-c14392c91e8d.png)

**Comment by blairlierman** [comment]
We (the WSU Foundation) are embedding iDonate in the WSU WordPress site using [this shortcode](https://github.com/washingtonstateuniversity/WSUWP-Plugin-Embeds/blob/master/includes/wsu-embed-idonate.php).

The problem with changing that option is that it reduces the space on the **left** side as well as the right side and makes the content looked "squished". 

Can the shortcode change or override that setting or is it something that would have to be changed in the theme?

**Comment by charlesjdillon** [comment]
It looks like Nate left a way to do a narrow gutter on [https://github.com/washingtonstateuniversity/WSU-spine/wiki/II.2.-Page:-Size,-Layouts,-and-Grids#gutters](https://github.com/washingtonstateuniversity/WSU-spine/wiki/II.2.-Page:-Size,-Layouts,-and-Grids#gutters). 

If that doesn't help then I would probably target the section with `section.customclass .side-right.gutter.column.one:not(.gutterless){padding-right:1em;}`

**Comment by blairlierman** [comment]
Thanks, that link and code example were what I needed to get the embed working with my plugin.
