### ISSUE TITLE
Main header text is not wrapping

### ISSUE THREAD

**Issue by MichelleFelt** [washingtonstateuniversity/WSUWP-spine-parent-theme#81]
I don't know if it's a case of the site title being too long, but this should wrap to the next line.

![afw-nowrap](https://cloud.githubusercontent.com/assets/6111174/3742208/ca7a6f7e-1766-11e4-89df-5d7bf2280185.gif)

**Comment by jeremyfelt** [comment]
I did another gif not thinking this existed already. Still an issue. :)

![bookmark-long-title](https://cloud.githubusercontent.com/assets/286171/8011673/6aa87250-0b6f-11e5-9ae6-8da6f50c0ece.gif)

**Comment by jeremyfelt** [comment]
@slocker3 @natejacobson opinions on how we could resolve this? Shrink text or wrap on mobile?

**Comment by jeremyfelt** [comment]
`.main-header` is set at a static 2000px width, even on mobile. The text has no chance to wrap. We should set this to `width: 100%;` at some point.

**Comment by jeremyfelt** [comment]
Probably whenever the bookmark is flush left

**Comment by jeremyfelt** [comment]
Nevermind your notifications :)
